logging:
  level:
    org.springframework.web: ERROR
    com.aaron: DEBUG
email: test@aaron.com
thread-pool: 10
app:
  menus:
    - title: Home
      name: Home
      path: /
    - title: Login
      name: Login
      path: /login
  compiler:
    timeout: 5
    output-folder: /temp/
  error: /error/